package com.spring.aichat.exception;

/**
 * 에러 코드 표준화
 *
 * [Phase 5] CONTENT_BLOCKED 추가 — 콘텐츠 모더레이션 차단
 */
public enum ErrorCode {
    BAD_REQUEST,
    NOT_FOUND,
    INSUFFICIENT_ENERGY,
    EXTERNAL_API_ERROR,
    INTERNAL_ERROR,

    // Phase 5: Payment
    PAYMENT_AMOUNT_MISMATCH,
    PAYMENT_ALREADY_PROCESSED,
    PAYMENT_VERIFICATION_FAILED,
    ORDER_NOT_FOUND,

    // Phase 5: Verification
    VERIFICATION_TOKEN_FAILED,
    VERIFICATION_DECRYPT_FAILED,
    VERIFICATION_UNDERAGE,
    VERIFICATION_DUPLICATE_CI,
    VERIFICATION_EXPIRED,
    VERIFICATION_ALREADY_DONE,

    // Phase 5: Content Moderation
    CONTENT_BLOCKED
}