-- V12 · UGC 세계관 빌더: 월드·장소·생성 잡 + characters/character_creation_jobs 연결 컬럼 (additive only)
-- (IF NOT EXISTS 전면 적용: 빈 로컬 DB 2단계 부팅 시 Hibernate(ddl-auto=update)가 먼저 만든
--  스키마 위로 baseline 이후 마이그레이션이 재생되므로 전 문장이 멱등이어야 한다 — V11과 동일 이유.)

-- 유저 생성 세계관 (재사용 자산 — 1 월드 : N 캐릭터. 기존 worlds는 enum PK라 별도 테이블)
CREATE TABLE IF NOT EXISTS ugc_worlds (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id  BIGINT       NOT NULL,               -- FK 미설정(Long 참조) 관례
    name           VARCHAR(50)  NOT NULL,
    intro          TEXT,
    lore           TEXT,                                -- 채팅 시스템 프롬프트 주입용
    mood_tags      VARCHAR(200),                        -- 콤마 구분 (worlds.mood_keywords 관례)
    thumbnail_url  VARCHAR(500),                        -- 서비스 CDN 공개 URL
    review_status  VARCHAR(20)  NOT NULL DEFAULT 'NONE', -- WorldReviewStatus (캐릭터 공개 심사 피기백)
    review_note    VARCHAR(500),
    created_at     TIMESTAMP    NOT NULL,
    updated_at     TIMESTAMP    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_ugc_world_owner ON ugc_worlds (owner_user_id);

-- 월드 장소 (world_locations의 UGC 변형 — 대표 배경 1장 직접 보유)
CREATE TABLE IF NOT EXISTS ugc_world_locations (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ugc_world_id      BIGINT       NOT NULL,
    location_key      VARCHAR(50)  NOT NULL,            -- 월드 내 unique SCREAMING_SNAKE_CASE
    display_name      VARCHAR(100) NOT NULL,
    description       TEXT,
    background_prompt TEXT,
    background_url    VARCHAR(500),                     -- 대표 배경 1장 (CDN 공개 URL)
    display_order     INTEGER      NOT NULL DEFAULT 0,
    is_active         BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_ugc_world_location_key UNIQUE (ugc_world_id, location_key)
);
CREATE INDEX IF NOT EXISTS idx_ugc_world_location_world ON ugc_world_locations (ugc_world_id, display_order);

-- 월드 생성 잡 (character_creation_jobs의 축소판 — 캐릭터 잡과 독립 병행)
CREATE TABLE IF NOT EXISTS ugc_world_creation_jobs (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                  BIGINT       NOT NULL,
    status                   VARCHAR(30)  NOT NULL,     -- WorldCreationJobStatus
    requested_name           VARCHAR(50),
    mood_hint                VARCHAR(200),
    concept_input_raw        TEXT         NOT NULL,
    structured_world_json    TEXT,                      -- W0 산출 전체
    draft_world_json         TEXT,                      -- W1 유저 편집 드래프트 (장소 상한 10)
    illustration_assets_json TEXT,                      -- {thumbnail, locations{KEY}} — 리롤 누적 버전 히스토리
    external_jobs_json       TEXT,                      -- Map<token, "PENDING"|fal requestId> — 제출 전 선커밋
    energy_charged           INT          NOT NULL DEFAULT 0,
    retry_count              INT          NOT NULL DEFAULT 0,
    fail_reason              VARCHAR(1000),
    ugc_world_id             BIGINT,                    -- READY 시 확정
    expires_at               TIMESTAMP,
    created_at               TIMESTAMP    NOT NULL,
    updated_at               TIMESTAMP    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_uwcj_user    ON ugc_world_creation_jobs (user_id);
CREATE INDEX IF NOT EXISTS idx_uwcj_status  ON ugc_world_creation_jobs (status);
CREATE INDEX IF NOT EXISTS idx_uwcj_expires ON ugc_world_creation_jobs (expires_at);

-- Hibernate(ddl-auto=update)가 먼저 테이블을 만든 로컬 DB의 enum CHECK 선제 제거 (V10/V11 관례 —
-- 이후 enum 값 추가 마이그레이션이 이 제약에 걸리는 함정 예방. 앱 레벨 enum이 값을 보장.)
ALTER TABLE ugc_world_creation_jobs DROP CONSTRAINT IF EXISTS ugc_world_creation_jobs_status_check;
ALTER TABLE ugc_worlds DROP CONSTRAINT IF EXISTS ugc_worlds_review_status_check;
-- requested_world_id(WorldId enum)도 동일 — 공식 세계관 5종째 추가 시 INSERT가 깨지는 함정 예방
ALTER TABLE character_creation_jobs DROP CONSTRAINT IF EXISTS character_creation_jobs_requested_world_id_check;

-- characters: UGC 월드 연결 (공식 연결은 기존 world_id enum 컬럼 그대로 — 병행, 앱 레벨 XOR 가드)
ALTER TABLE characters ADD COLUMN IF NOT EXISTS ugc_world_id BIGINT;
CREATE INDEX IF NOT EXISTS idx_char_ugc_world ON characters (ugc_world_id);

-- character_creation_jobs: 위저드 컨셉 스텝의 세계관 3택(공식 4종 | 내 커스텀 월드 | 나중에 연결) 요청 보관
-- → Stage 4 바인딩에서 Character에 주입
ALTER TABLE character_creation_jobs ADD COLUMN IF NOT EXISTS requested_world_id     VARCHAR(50); -- WorldId enum
ALTER TABLE character_creation_jobs ADD COLUMN IF NOT EXISTS requested_ugc_world_id BIGINT;
