-- V1 · Phase 6 Phase A: 관리자 행위 감사 로그
-- 기존 스키마는 Flyway baseline(version 0)으로 처리되며, 본 마이그레이션부터 신규 오브젝트만 버전 관리한다.
-- 컬럼 타입은 Hibernate(Postgres) 매핑과 일치시켜 prod의 ddl-auto=validate 통과를 보장한다.
-- 표준 SQL(IDENTITY/TEXT/TIMESTAMP)만 사용하여 H2 테스트와도 호환된다.

CREATE TABLE audit_logs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id  BIGINT,
    actor_username VARCHAR(100) NOT NULL,
    action         VARCHAR(60)  NOT NULL,
    target_type    VARCHAR(40),
    target_id      VARCHAR(100),
    summary        VARCHAR(500),
    detail_json    TEXT,
    created_at     TIMESTAMP    NOT NULL
);

CREATE INDEX idx_audit_created_at ON audit_logs (created_at);
CREATE INDEX idx_audit_actor      ON audit_logs (actor_username);
CREATE INDEX idx_audit_action     ON audit_logs (action);
CREATE INDEX idx_audit_target     ON audit_logs (target_type, target_id);
