-- [2026-08-04 페르소나 풀 패키지] 유저 페르소나 카드 (신규 아이디어 ③, 종원 확정)
-- Theater에서 검증된 재미(페르소나 튜닝 + 5축 스탯 + Persona–Stat Hybrid 망상 규칙)를
-- 전 모드 자산으로 제품화 — 카드는 유저 소유 재사용 자산, 방에는 스냅샷으로 복사(소급 불변).

CREATE TABLE IF NOT EXISTS user_personas (
    persona_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL,             -- FK 미설정 Long 참조(V2 도메인 관례)
    name           VARCHAR(30)  NOT NULL,             -- 카드명 (예: "힘을 숨긴 대마법사")
    gender         VARCHAR(10),                       -- FEMALE/MALE — 씬 렌더 유저 표현 기준(null=MALE 레거시 폴백)
    persona_text   TEXT         NOT NULL,             -- 페르소나 본문 (room.user_persona로 스냅샷)
    stat_charm     INT          NOT NULL DEFAULT 0,   -- 5축 스탯 — Theater AvatarStat 체계 공유
    stat_wit       INT          NOT NULL DEFAULT 0,
    stat_boldness  INT          NOT NULL DEFAULT 0,
    stat_intellect INT          NOT NULL DEFAULT 0,
    stat_empathy   INT          NOT NULL DEFAULT 0,
    created_at     TIMESTAMP    NOT NULL,
    updated_at     TIMESTAMP    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_user_persona_owner ON user_personas (user_id);

-- 방 스냅샷 — 카드 수정이 진행 중 방을 소급 변경하지 않게 생성 시점 값 복사(Theater 관례).
-- persona_text는 기존 chat_rooms.user_persona 재사용(프롬프트 배관 기존재), 스탯·성별만 신설.
ALTER TABLE chat_rooms ADD COLUMN IF NOT EXISTS persona_stats_json TEXT;
ALTER TABLE chat_rooms ADD COLUMN IF NOT EXISTS persona_gender VARCHAR(10);
ALTER TABLE chat_rooms DROP CONSTRAINT IF EXISTS chat_rooms_persona_gender_check;
