-- V3 · Phase 6 Phase E: 유저 인앱 알림 (폴링 기반, user-keyed)
-- 기존 OffscreenNotification 은 방-스코프/스토리 전용이라 재사용 불가 → user_id 키의 신규 테이블.
CREATE TABLE notifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    type       VARCHAR(40)  NOT NULL,
    title      VARCHAR(200) NOT NULL,
    body       TEXT,
    link_type  VARCHAR(40),
    link_id    VARCHAR(100),
    read_at    TIMESTAMP,
    created_at TIMESTAMP    NOT NULL
);

CREATE INDEX idx_notification_user   ON notifications (user_id);
CREATE INDEX idx_notification_unread ON notifications (user_id, read_at);
