-- V4 · Phase 6 Phase E: CS 티켓 + 답변 스레드
CREATE TABLE support_tickets (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL,
    type         VARCHAR(20)  NOT NULL,   -- INQUIRY / FEEDBACK / BUG
    category     VARCHAR(60),
    subject      VARCHAR(200) NOT NULL,
    body         TEXT         NOT NULL,
    status       VARCHAR(20)  NOT NULL,   -- OPEN / IN_PROGRESS / RESOLVED
    assignee     VARCHAR(100),
    context_json TEXT,                    -- 제출 시 로그인 컨텍스트 / 신고 로그 컨텍스트 스냅샷
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP    NOT NULL
);

CREATE INDEX idx_ticket_user   ON support_tickets (user_id);
CREATE INDEX idx_ticket_status ON support_tickets (status);
CREATE INDEX idx_ticket_type   ON support_tickets (type);

CREATE TABLE support_ticket_replies (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id   BIGINT       NOT NULL,
    author_type VARCHAR(20)  NOT NULL,    -- USER / ADMIN
    author_name VARCHAR(100) NOT NULL,
    body        TEXT         NOT NULL,
    created_at  TIMESTAMP    NOT NULL
);

CREATE INDEX idx_reply_ticket ON support_ticket_replies (ticket_id);
