-- V5 · Phase 6 Phase E: 편집형 QnA(FAQ)
CREATE TABLE faq_entries (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category      VARCHAR(60)  NOT NULL,
    question      VARCHAR(300) NOT NULL,
    answer        TEXT         NOT NULL,
    display_order INTEGER      NOT NULL DEFAULT 0,
    published     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL
);

CREATE INDEX idx_faq_published ON faq_entries (published, category, display_order);
