-- V7 · Phase 6 Phase F: 모더레이션 / 프롬프트 인젝션 이벤트 영속화
-- 기존에는 라이브 채팅 차단이 log.warn 로만 남았음(리뷰 큐 불가). 관리자 리뷰 큐 + 반복위반 집계용.

CREATE TABLE moderation_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT,
    room_id         BIGINT,
    source          VARCHAR(20),      -- CHAT / CHAT_V2 / THEATER
    blocked_at_step INTEGER NOT NULL, -- 1=키워드, 2=OpenAI
    category        VARCHAR(80),
    message         TEXT,             -- 원문(운영 리뷰용). 보존정책 검토 대상.
    latency_ms      BIGINT,
    created_at      TIMESTAMP NOT NULL
);
CREATE INDEX idx_mod_user    ON moderation_events (user_id);
CREATE INDEX idx_mod_created ON moderation_events (created_at);

CREATE TABLE injection_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT,
    username        VARCHAR(50),
    room_id         BIGINT,
    source          VARCHAR(20),
    severity        VARCHAR(20),      -- EXTRACTION / CRITICAL
    matched_pattern VARCHAR(500),
    message         TEXT,
    created_at      TIMESTAMP NOT NULL
);
CREATE INDEX idx_inj_user    ON injection_events (user_id);
CREATE INDEX idx_inj_created ON injection_events (created_at);
