-- V9 · UGC v1: 캐릭터 생성 잡 + characters UGC 컬럼 (additive only)

CREATE TABLE character_creation_jobs (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                  BIGINT       NOT NULL,
    status                   VARCHAR(30)  NOT NULL,   -- CreationJobStatus
    requested_name           VARCHAR(50),
    concept_input_raw        TEXT         NOT NULL,
    structured_concept_json  TEXT,                    -- Stage 0 산출 전체
    bg_color                 VARCHAR(40),
    golden_shot_keys_json    TEXT,                    -- 서비스 S3 키 배열
    selected_golden_shot_key VARCHAR(500),
    base_standing_key        VARCHAR(500),
    emotion_assets_json      TEXT,                    -- Map<EmotionTag,{key,status,retryCount}>
    external_jobs_json       TEXT,                    -- RunPod/fal 잡 추적 (디버깅·폴링 폴백)
    base_edit_seed           BIGINT,
    energy_charged           INT          NOT NULL DEFAULT 0,
    retry_count              INT          NOT NULL DEFAULT 0,
    fail_reason              VARCHAR(1000),
    character_id             BIGINT,
    expires_at               TIMESTAMP,
    created_at               TIMESTAMP    NOT NULL,
    updated_at               TIMESTAMP    NOT NULL
);

CREATE INDEX idx_ccj_user    ON character_creation_jobs (user_id);
CREATE INDEX idx_ccj_status  ON character_creation_jobs (status);
CREATE INDEX idx_ccj_expires ON character_creation_jobs (expires_at);

-- characters 확장: 소유·공개·Secret 심사 (기존 행 = 공식 캐릭터)
ALTER TABLE characters ADD COLUMN owner_user_id        BIGINT;
ALTER TABLE characters ADD COLUMN source               VARCHAR(20) NOT NULL DEFAULT 'OFFICIAL';
ALTER TABLE characters ADD COLUMN secret_eligible      BOOLEAN     NOT NULL DEFAULT FALSE;
ALTER TABLE characters ADD COLUMN visibility           VARCHAR(20) NOT NULL DEFAULT 'PUBLIC';
ALTER TABLE characters ADD COLUMN secret_review_status VARCHAR(20) NOT NULL DEFAULT 'NONE';
ALTER TABLE characters ADD COLUMN review_note          VARCHAR(500);

-- 기존(공식) 캐릭터는 Secret 허용 유지 — user-global 게이트만으로 동작하던 현행 의미 보존
UPDATE characters SET secret_eligible = TRUE;

CREATE INDEX idx_char_owner      ON characters (owner_user_id);
CREATE INDEX idx_char_visibility ON characters (visibility);
